### PR TITLE
extract transaction stages from uport indexjs

### PR DESCRIPTION
**Pull request by Stefvan**
changed uport index.js to return object containing stages of transaction

### CODE REVIEW

**Comment by vongohren** [comment]
@Stefvan I think there might be a bug here: https://photos.app.goo.gl/iteuFuua27Lfl2Lz1

Not sure if these are suppose to be in the different stages?

**Comment by Stefvan** [comment]
Hi @vongohren sorry for leaving it unexplained. We are trying to show the different stages of the transaction during its lifecycle up-to the final result.

**Comment by vongohren** [comment]
@Stefvan I understand, but it seems that everything is now happening in stage 3. I believe they should be split up?

**Comment by Stefvan** [comment]
@vongohren You're right. I made a new pr with this fixed.

**Pull request merged**
